#include <stdio.h>
#include <string.h>
#include "handlers.h"
#include "../messaging/chatroom.h"
#include "../messaging/direct.h"
#include "../network/peer_manager.h"

/*
 * handle_get_stats - return JSON with current system state
 * - open and parse /proc/keycipher/stats for buffer levels
 * - call peer_manager_get_all() for peer statuses
 * - call chatroom_get_semaphore_count() for live semaphore value
 * - build JSON: { incoming_used, incoming_free, chatroom_used,
 *                 chatroom_free, semaphore_count, peers: [...] }
 * - write HTTP 200 + JSON to client_fd
 */
void handle_get_stats(int client_fd) {
    //open /proc/keycipher/stats file generated by proc_stats
    FILE *fp = fopen("/proc/keycipher/stats", "r");
    if (!fp) {
        dprintf(client_fd, "HTTP/1.1 500 Internal Server Error\r\n\r\n");
        return;
    }

    //TODO: make sure proc file exists pls

    int incoming_used=0, incoming_free=0;
    int outgoing_used=0, outgoing_free=0;
    int chatroom_used=0, chatroom_free=0;
    int total_sent=0, total_received=0, total_blocked=0;

    //parse lines for info
    char line[128];
    while (fgets(line, sizeof(line), fp)) {
        sscanf(line, "incoming_used: %d", &incoming_used);
        sscanf(line, "incoming_free: %d", &incoming_free);
        sscanf(line, "outgoing_used: %d", &outgoing_used);
        sscanf(line, "outgoing_free: %d", &outgoing_free);
        sscanf(line, "chatroom_used: %d", &chatroom_used);
        sscanf(line, "chatroom_free: %d", &chatroom_free);
        sscanf(line, "total_sent: %d", &total_sent);
        sscanf(line, "total_received: %d", &total_received);
        sscanf(line, "total_blocked: %d", &total_blocked);
    }
    fclose(fp);
    //note: i'm scanning the total sent/received/blocked, not sure whether to include in stats or keep json packet sent low content

    //fetch semaphore count
    int sema_count = chatroom_get_semaphore_count();

    //fetch peers info
    char peers_json[2048]; //max size is easier than dynamic sizing for string
    peers_json[0] = '\0';  //start empty

    strcat(peers_json, "[");  //begin array

    peer_t *peers = peer_manager_get_all();
    int peer_count = peer_manager_count();

    for (int i = 0; i < peer_count; i++) {
        char entry[256];

        // Convert enum to string
        const char *status_str =
            (peers[i].status == PEER_CONNECTED) ? "connected" :
            (peers[i].status == PEER_BLOCKED)   ? "blocked" :
                                                "offline";

        snprintf(entry, sizeof(entry),
            "{\"ip\":\"%s\",\"port\":%d,\"status\":\"%s\"}",
            peers[i].ip,
            peers[i].port,
            status_str
        );

        strcat(peers_json, entry);

        if (i < peer_count - 1)
            strcat(peers_json, ",");
    }

    strcat(peers_json, "]");

    //create JSON using data
    char json[4096];
    snprintf(json, sizeof(json),
        "{"
        "\"incoming_used\": %d,"
        "\"incoming_free\": %d,"
        "\"chatroom_used\": %d,"
        "\"chatroom_free\": %d,"
        "\"total_sent\": %d,"
        "\"total_received\": %d,"
        "\"total_blocked\": %d,"
        "\"semaphore_count\": %d,"
        "\"peers\": %s"
        "}",
        incoming_used, incoming_free,
        chatroom_used, chatroom_free,
        total_sent, total_received, total_blocked, 
        sema_count, peers_json
    );

    dprintf(client_fd,
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: application/json\r\n"
        "Content-Length: %zu\r\n\r\n"
        "%s",
        strlen(json), json
    );
}

/*
 * handle_get_messages - return JSON list of messages in incoming FIFO
 * - read message queue from userspace buffer (populated by direct_receive_loop)
 * - build JSON array: [{ id, sender, timestamp, encrypted_preview }]
 * - write HTTP 200 + JSON to client_fd
 * NOTE: messages are NOT decrypted here, only previewed as encrypted (?)
 */
void handle_get_messages(int client_fd) {
    user_msg_t *msgs = direct_get_messages(); //TODO: make sure direct.c has new additions
    int count = direct_get_message_count();

    //create JSON
    char json[4096];
    json[0] = '\0';        //start empty

    strcat(json, "[");     //begin array

    for (int i = 0; i < count; i++) {
        char entry[512];

        // Format one message entry
        snprintf(entry, sizeof(entry),
            "{\"id\": %d,"
             "\"sender\": \"%s\","
             "\"timestamp\": %ld,"
             "\"encrypted_preview\": \"%s\"}",
            msgs[i].id,
            msgs[i].sender,
            msgs[i].timestamp,
            msgs[i].encrypted_preview
        );

        strcat(json, entry);

        if (i < count - 1)
            strcat(json, ",");
    }
    strcat(json, "]");


    dprintf(client_fd,
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: application/json\r\n"
        "Content-Length: %zu\r\n\r\n"
        "%s",
        strlen(json), json
    );
}

/*
 * handle_get_chatroom - return JSON list of chatroom messages
 * - similar to handle_get_messages but for chatroom buffer
 * - include semaphore_count in response so UI can show live counter
 */
void handle_get_chatroom(int client_fd) {
    //fetch chatroom messages
    chat_msg_t *msgs = chatroom_get_messages(); //TODO: make sure its implemented
    int count = chatroom_get_message_count();

    //fetch semaphore count
    int sema_count = chatroom_get_semaphore_count();

    //build JSON
    char json[4096];
    json[0] = '\0';
    strcat(json, "{");
    
    //add semaphore count first
    char sema_entry[64];
    snprintf(sema_entry, sizeof(sema_entry),
             "\"semaphore_count\": %d, \"messages\": [",
             sema_count);
    strcat(json, sema_entry);

    //adding message entries
    for (int i = 0; i < count; i++) {
        char entry[512];

        snprintf(entry, sizeof(entry),
            "{\"id\": %d,"
             "\"sender\": \"%s\","
             "\"timestamp\": %ld,"
             "\"encrypted_preview\": \"%s\"}",
            msgs[i].id,
            msgs[i].sender,
            msgs[i].timestamp,
            msgs[i].encrypted_preview
        );

        strcat(json, entry);

        if (i < count - 1)
            strcat(json, ",");
    }
    strcat(json, "]}");

    dprintf(client_fd,
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: application/json\r\n"
        "Content-Length: %zu\r\n\r\n"
        "%s",
        strlen(json), json
    );
}

/*
 * handle_read_one - decrypt and return one specific message
 * - find message by id in userspace queue
 * - open /dev/keycipher_in, trigger ioctl for single read
 * - kernel decrypts and returns plaintext
 * - this frees one FIFO slot: semaphore count increases
 * - any blocked remote peer that was waiting for space will now unblock
 * - return JSON: { id, sender, plaintext, timestamp }
 */
void handle_read_one(int client_fd, const char *message_id) {
    int id = atoi(message_id); //ascii/string to integer

    //find message in userspace queue
    user_msg_t *msg = direct_find_message_by_id(id);
    if (!msg) {
        dprintf(client_fd,
            "HTTP/1.1 404 Not Found\r\n"
            "Content-Type: text/plain\r\n"
            "Content-Length: 15\r\n\r\n"
            "Message not found");
        return;
    }

    //kernel decryption
    //TODO: check this even works!
    kernel_msg_t kmsg;
    int fd = open("/dev/keycipher_in", O_RDONLY); //open as read only
    if (fd < 0) {
        perror("handle_read_one: open");
        dprintf(client_fd, "HTTP/1.1 500 Internal Server Error\r\n\r\n");
        return;
    }
    int bytes = read(fd, &kmsg, sizeof(kmsg));
    close(fd);

    if (bytes <= 0) {
        perror("handle_read_one: read");
        dprintf(client_fd, "HTTP/1.1 500 Internal Server Error\r\n\r\n");
        return;
    }

    //build JSON
    char json[512];
    snprintf(json, sizeof(json),
        "{"
        "\"id\": %d,"
        "\"sender\": \"%s\","
        "\"timestamp\": %ld,"
        "\"plaintext\": \"%.*s\""
        "}",
        msg->id,
        msg->sender,
        msg->timestamp,
        kmsg.len,
        kmsg.data
    );

    dprintf(client_fd,
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: application/json\r\n"
        "Content-Length: %zu\r\n\r\n"
        "%s",
        strlen(json), json
    );
}

/*
 * handle_read_all - flush entire incoming FIFO
 * - open /dev/keycipher_in
 * - ioctl(fd, KEYCIPHER_FLUSH_IN)
 * - kernel decrypts all messages and returns them
 * - all FIFO slots freed: semaphore jumps to full capacity
 * - all blocked remote peers unblock simultaneously
 * - return JSON array of all decrypted messages
 */
void handle_read_all(int client_fd) { //TODO: REVIEW CODE
    // 1. Open device
    int fd = open("/dev/keycipher_in", O_RDONLY);
    if (fd < 0) {
        perror("handle_read_all: open");
        dprintf(client_fd, "HTTP/1.1 500 Internal Server Error\r\n\r\n");
        return;
    }

    // 2. Trigger flush ioctl
    if (ioctl(fd, KEYCIPHER_FLUSH_IN) < 0) {
        perror("handle_read_all: ioctl");
        close(fd);
        dprintf(client_fd, "HTTP/1.1 500 Internal Server Error\r\n\r\n");
        return;
    }

    // 3. Read all decrypted messages
    kernel_msg_t msgs[64];   // adjust to your FIFO capacity
    int bytes = read(fd, msgs, sizeof(msgs));
    close(fd);

    if (bytes < 0) {
        perror("handle_read_all: read");
        dprintf(client_fd, "HTTP/1.1 500 Internal Server Error\r\n\r\n");
        return;
    }

    int msg_count = bytes / sizeof(kernel_msg_t);

    // 4. Build JSON array
    char json[8192];
    json[0] = '\0';
    strcat(json, "[");

    for (int i = 0; i < msg_count; i++) {
        char entry[512];

        snprintf(entry, sizeof(entry),
            "{\"id\": %d,"
             "\"sender\": \"%s\","
             "\"timestamp\": %lld,"
             "\"plaintext\": \"%.*s\"}",
            i + 1,                       // or match to userspace IDs
            msgs[i].author,
            msgs[i].tv_sec,
            msgs[i].len,
            msgs[i].data
        );

        strcat(json, entry);
        if (i < msg_count - 1)
            strcat(json, ",");
    }

    strcat(json, "]");

    // 5. Send HTTP response
    dprintf(client_fd,
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: application/json\r\n"
        "Content-Length: %zu\r\n\r\n"
        "%s",
        strlen(json), json
    );
}

/*
 * handle_send_direct - send a direct message to a specific peer
 * - parse body JSON for { target_ip, message }
 * - find peer by ip in peers[]
 * - call direct_send(peer, message)
 * - return JSON: { status, encrypted_preview }
 */
void handle_send_direct(int client_fd, const char *body){
    //TODO: body contains raw JSON from Node.js, parse it here

    char json[256];
    snprintf(json, sizeof(json),
        "{ \"status\": \"sent\", \"preview\": \"encrypted...\" }"
    );

    dprintf(client_fd,
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: application/json\r\n"
        "Content-Length: %zu\r\n\r\n"
        "%s",
        strlen(json), json
    );

    /* TODO: implement direct send handler */
}

/*
 * handle_send_chatroom - broadcast a message to all peers via chatroom
 * - parse body JSON for { message }
 * - call chatroom_send(message)
 * - return JSON: { status, encrypted_preview, peers_notified }
 */
void handle_send_chatroom(int client_fd, const char *body)
{
    /* TODO: implement chatroom send handler */
}
